version: '3.0'

services:
  database:
    container_name: mongodb_api_smatranking
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: smatranking
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongodb_api_smatranking
